### ISSUE TITLE
Contact information

### ISSUE THREAD

**Issue by 6XoCtujg2C0gne** [PierreMasselot1/Material-Switching-Unit#1]
Hello Pierre!
Can you kindly provide some contact information so that we can correspond with you?
Thanks in advance!
Paul

**Comment by PierreMasselot1** [comment]
Hey,
I created a discord server so that people can ask questions, provide ideas and report bugs etc.
Here is the link to the server: https://discord.gg/Pj8bwTn
If you want to contact me privately, you can do so either on discord(Stonemile#6906) or email me at: pierre.masselot.d@gmail.com
Pierre
